<a href="https://colab.research.google.com/github/imaneJHX/IPM-v0-main/blob/main/Football_Match_Outcome_Predictor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%pip install -q pandas numpy scikit-learn matplotlib seaborn joblib requests

In [2]:
import pandas as pd
from pathlib import Path

In [3]:
import pandas as pd

seasons = range(19, 26)
frames = []

for year in seasons:
    season = f"{year:02d}{year + 1:02d}"

    url = (
        f"https://www.football-data.co.uk/"
        f"mmz4281/{season}/E0.csv"
    )

    try:
        df = pd.read_csv(url, encoding="cp1252")
        frames.append(df)
        print(f"Season {season}: downloaded successfully")

    except Exception as error:
        print(f"Season {season}: could not download - {error}")

if not frames:
    raise RuntimeError("No data downloaded. Check your connection.")

data = pd.concat(frames, ignore_index=True)

print("Total rows:", len(data))
display(data.head())

Season 1920: downloaded successfully
Season 2021: downloaded successfully
Season 2122: downloaded successfully
Season 2223: downloaded successfully
Season 2324: downloaded successfully
Season 2425: downloaded successfully
Season 2526: downloaded successfully
Total rows: 2660

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,BMGMCA,BVCH,BVCD,BVCA,CLCH,CLCD,CLCA,LBCH,LBCD,LBCA
0,E0,09/08/2019,20:00,Liverpool,Norwich,4,1,H,4,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,E0,10/08/2019,12:30,West Ham,Man City,0,5,A,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,E0,10/08/2019,15:00,Bournemouth,Sheffield United,1,1,D,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,E0,10/08/2019,15:00,Burnley,Southampton,3,0,H,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,E0,10/08/2019,15:00,Crystal Palace,Everton,0,0,D,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# Select only the columns needed for our project
data = data[
    ["Date", "HomeTeam", "AwayTeam", "FTHG", "FTAG", "FTR"]
].copy()

# Display the first five rows
display(data.head())

         Date        HomeTeam          AwayTeam  FTHG  FTAG FTR
0  09/08/2019       Liverpool           Norwich     4     1   H
1  10/08/2019        West Ham          Man City     0     5   A
2  10/08/2019     Bournemouth  Sheffield United     1     1   D
3  10/08/2019         Burnley       Southampton     3     0   H
4  10/08/2019  Crystal Palace           Everton     0     0   D

In [6]:
print(data["FTR"].value_counts())
print("\nPercentages:")
print((data["FTR"].value_counts(normalize=True) * 100).round(2))

FTR
H    1155
A     876
D     629
Name: count, dtype: int64

Percentages:
FTR
H    43.42
A    32.93
D    23.65
Name: proportion, dtype: float64